import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import type {
  HealthCheckDetail,
  HealthCheckStatus,
} from '../instrumentation/health-check.types';

/**
 * Database schema for austv-sales (spec section 4).
 *
 * Design invariants enforced here (see .specs/project/PROJECT.md §4, §7):
 * - `sales.id` is a client-supplied UUID (generated by the plugin) — no DB default.
 *   The primary key is the sole idempotency guard against the SQLite queue replay.
 * - `sales.item_id` references `items.item_id` (the opaque business key), not `items.id`.
 * - `purchased_at` comes from the plugin payload; `created_at` is stamped by the DB
 *   so we can audit queue latency without polluting the real purchase timestamp.
 * - All timestamps are `timestamptz` (clock-skew / America/Sao_Paulo correctness).
 * - All foreign keys are ON DELETE NO ACTION (the pg default): a category cannot be
 *   deleted while items reference it, nor an item while sales reference it. Catalog is
 *   deactivated (`active = false`), never hard-deleted — historical sales stay intact.
 */

export const categories = pgTable(
  'categories',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    name: text('name').notNull(),
    displayOrder: integer('display_order').notNull().default(0),
  },
  (table) => [
    // Case-insensitive uniqueness of the category name (spec S4.0). The service
    // pre-checks to produce a friendly 409, but the check-then-insert pair is a
    // race: this index is the data-layer guarantee that a duplicate can never
    // land, no matter how the write arrives.
    uniqueIndex('categories_name_lower_unique').on(sql`lower(${table.name})`),
  ],
);

export const items = pgTable('items', {
  id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
  itemId: text('item_id').notNull().unique(),
  displayName: text('display_name').notNull(),
  categoryId: integer('category_id')
    .notNull()
    .references(() => categories.id),
  active: boolean('active').notNull().default(true),
});

export const players = pgTable('players', {
  uuid: uuid('uuid').primaryKey(),
  lastKnownNickname: text('last_known_nickname').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const sales = pgTable(
  'sales',
  {
    // Client-supplied UUID (plugin-generated). No default: the plugin owns the id
    // so that reprocessing the SQLite fallback queue is idempotent (spec §3, §7).
    id: uuid('id').primaryKey(),
    itemId: text('item_id')
      .notNull()
      .references(() => items.itemId),
    playerUuid: uuid('player_uuid')
      .notNull()
      .references(() => players.uuid),
    nicknameAtPurchase: text('nickname_at_purchase').notNull(),
    totalPrice: numeric('total_price', { precision: 12, scale: 2 }).notNull(),
    qtd: integer('qtd').notNull(),
    purchasedAt: timestamp('purchased_at', { withTimezone: true }).notNull(),
    historicalImport: boolean('historical_import').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index('sales_item_purchased_at_idx').on(table.itemId, table.purchasedAt),
    index('sales_player_item_idx').on(table.playerUuid, table.itemId),
    // Data-layer defense for financial integrity (spec §2, §7): a bug or a
    // replayed queue entry must never persist a non-positive amount/quantity.
    check('sales_qtd_positive', sql`${table.qtd} > 0`),
    check('sales_total_price_positive', sql`${table.totalPrice} > 0`),
  ],
);

/**
 * Instrumentation health checks (AusTV Admin spec §6.1, ADR-006 — story S6.3).
 *
 * The table is **append-only**: one row per check execution. That choice is the
 * whole point of ADR-006 — every disaster found at AusTV was silent for months,
 * so "what did this check say last week?" has to be answerable. Keeping a
 * current-state row and overwriting it would answer only "what does it say now",
 * which is exactly the blindness the epic exists to remove. The current state of
 * a check is simply its most recent row.
 *
 * `alerted_at` is per-observation, not per-check: it records whether *this*
 * reading was announced on Discord. That is what lets the alerter group a
 * three-month outage into one notification instead of one per cycle, without
 * losing the fact that the check kept running the whole time.
 *
 * Table name is plural to match the rest of this schema; the spec §7 sketch
 * writes entities in the singular (`health_check`).
 */
export const healthChecks = pgTable(
  'health_checks',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    /** Stable identifier of the check (see `HealthCheckName`). */
    checkName: text('check_name').notNull().$type<string>(),
    status: text('status').notNull().$type<HealthCheckStatus>(),
    checkedAt: timestamp('checked_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    /**
     * Structured verdict. Deliberately jsonb rather than free text so a ratio can
     * always carry the `n` behind it — the spec rule is that no percentage is
     * ever published without its base.
     */
    detail: jsonb('detail').$type<HealthCheckDetail>(),
    /** When this observation produced a Discord alert; null means it did not. */
    alertedAt: timestamp('alerted_at', { withTimezone: true }),
  },
  (table) => [
    // Serves both access patterns: "latest row for this check" and "history of
    // this check", which are the only two ways this table is ever read.
    index('health_checks_name_checked_at_idx').on(
      table.checkName,
      table.checkedAt.desc(),
    ),
    // Serves the alert budget: "how much has this check said in the last N
    // hours", which filters on `alerted_at` and so cannot use the index above.
    // Partial because the overwhelming majority of rows are never announced —
    // on a healthy week every row has `alerted_at` null — so the index stays a
    // tiny fraction of the table it sits on.
    index('health_checks_name_alerted_at_idx')
      .on(table.checkName, table.alertedAt.desc())
      .where(sql`${table.alertedAt} IS NOT NULL`),
    // `no_data` and `error` exist as first-class states on purpose. A gap in
    // collection must never be recorded as `ok` (false confidence) nor as a zero
    // reading (a fabricated measurement) — the two failure modes ADR-006 targets.
    check(
      'health_checks_status_valid',
      sql`${table.status} IN ('ok', 'breached', 'no_data', 'error')`,
    ),
  ],
);

/**
 * Daily tutorial funnel, rebuilt from `Quests/playerdata` (story S8.0, ADR-0004).
 *
 * Two of the four funnel steps of spec §6.2 live here — `tutorial_entrou` and
 * `tutorial_concluiu` — because Plan collects nothing about the tutorial and no
 * API or database anywhere holds this. The source is the Quests plugin's own
 * per-player files on the game machine.
 *
 * ## Why the grain is `(date, platform)` and never a player
 *
 * The funnel asks "how many entered on day D, by platform". Storing a row per
 * player would put the game's player identities in this database for a question
 * that is answered by counting, and spec §8 keeps personal data out. The uuid is
 * read to derive `platform` (ADR-003) and then discarded.
 *
 * ## The table is REPLACED on every sync, not appended to
 *
 * The source is **current state, not an event log** — `playerdata` holds each
 * player's progress as it stands today. So every sync recomputes the whole
 * series from scratch, and re-running is the normal operation rather than a
 * recovery path. That is what makes the ETL idempotent (criterion 2 of S8.0).
 *
 * It also means the past can change: a deleted `playerdata` erases the day that
 * player entered, and a quest reset moves their `started-date`. The series is a
 * **reconstruction of the past from the present**, which is sound for detecting
 * that the entry rate collapsed and unsound for anything accounting-shaped.
 * Recorded in ADR-0004 rather than discovered later.
 *
 * ## Absence of a row is not automatically zero
 *
 * A date with no row means "nobody entered that day" **only if a successful sync
 * covers it**. Whether one does is answered by {@link tutorialSyncs}, which is
 * why that table exists and why readers must consult it before rendering a gap
 * as a zero — the confusion this whole epic exists to remove.
 */
export const tutorialDaily = pgTable(
  'tutorial_daily',
  {
    /** Calendar day in America/Sao_Paulo. Bucketed at write time. */
    day: date('day').notNull(),
    /**
     * `bedrock` | `java_offline` | `java_premium` | `unknown` (ADR-003).
     *
     * Written by the ETL and **read by no query in this application** — the read
     * paths recompute it from the uuid, so that ADR-003 has exactly one
     * implementation and it is the TypeScript one. It is kept because an
     * operator reading this table by hand needs the derived value beside the
     * uuid, and because the index below leads with `registered_at` anyway.
     *
     * No `CHECK` constraint: the only writer is `platformOf`, whose return type
     * is the union. A constraint would be a second spelling of that rule.
     */
    platform: text('platform').notNull(),
    /** Players whose earliest tutorial `started-date` fell on this day. */
    entered: integer('entered').notNull(),
    /** Players who completed the configured final quest on this day. */
    completed: integer('completed').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.day, table.platform] }),
    // Reads are always "the series between two dates", optionally filtered by
    // platform — the primary key already leads with `day`, so this index exists
    // only for the platform-first read the S8.1 segmentation performs.
    index('tutorial_daily_platform_day_idx').on(table.platform, table.day),
    check('tutorial_daily_entered_non_negative', sql`${table.entered} >= 0`),
    check(
      'tutorial_daily_completed_non_negative',
      sql`${table.completed} >= 0`,
    ),
  ],
);

/**
 * Provenance of each ETL run (story S8.0).
 *
 * Append-only, for the same reason `health_checks` is: the question "was this
 * number ever actually measured, and when?" has to be answerable. Without it,
 * an empty {@link tutorialDaily} is indistinguishable from a sync that has never
 * run — and reading the second as the first is how a collection gap becomes a
 * reported zero.
 *
 * `finalQuestId` is stored per run and not only in configuration because the
 * completion count is meaningless without knowing which quest was counted, and
 * that id is expected to change when the tutorial does (ADR-0004).
 */
export const tutorialSyncs = pgTable(
  'tutorial_syncs',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    ranAt: timestamp('ran_at', { withTimezone: true }).notNull().defaultNow(),
    /** `ok` — the series was rebuilt. `error` — nothing was written. */
    status: text('status').notNull().$type<'ok' | 'error'>(),
    /** Playerdata files read. Null on a run that never got that far. */
    filesScanned: integer('files_scanned'),
    /**
     * Files that failed to parse.
     *
     * Kept separate from `filesScanned` rather than folded into it: a run that
     * read 19.700 files and failed on 9.000 of them produced a number, and
     * whoever reads that number needs to know it covers half the corpus.
     */
    filesFailed: integer('files_failed'),
    /**
     * Players who touched at least one tutorial quest, dated or not.
     *
     * Stored because it is the **output-side** number the next run compares
     * against. A run that reads every file successfully and finds zero tutorial
     * players is what a renamed quest id looks like, and it is indistinguishable
     * from a real collapse unless the previous run's value is on record.
     */
    playersInTutorial: integer('players_in_tutorial'),
    /**
     * `(day, platform)` rows the run produced.
     *
     * On an `ok` row, what was written. On an `error` row, what the run *would*
     * have written before a floor rule stopped it — so the record says how close
     * it came, not merely that it stopped.
     *
     * Read by the next run: a collapse against this value is how partial loss of
     * dates is caught, and zero is refused outright. Both rules live in
     * `TutorialSyncService.floorRefusal`.
     */
    daysWritten: integer('days_written'),
    /** Tutorial quests found in the catalogue directory. */
    questsInCatalogue: integer('quests_in_catalogue'),
    /** Which quest was counted as completion on this run. */
    finalQuestId: text('final_quest_id'),
    /**
     * The step order this run resolved, as a comma-separated list of quest ids.
     *
     * Stored because `tutorial_player_position.furthest_index` is a position in
     * it, and that order is **inferred from the quest file names** rather than
     * read from the quests' own requirements. Writing it down is what lets
     * somebody check the inference against the game instead of trusting it — and
     * what makes a reordering visible as a diff between two runs.
     */
    stepOrder: text('step_order'),
    /** Rows written to `tutorial_player_position`, or null when disabled. */
    positionsWritten: integer('positions_written'),
    /**
     * Why an `error` run failed, in Portuguese. Never a stack trace.
     *
     * ⚠️ **Contains server-side absolute paths** — the failure messages name the
     * directory that could not be read, which is the single most useful thing
     * for whoever is debugging a mount. That is fine where it lives today (the
     * log and this table, neither reachable from a route) and **is not fine on a
     * response body**: spec §8 keeps internal topology out of the browser, the
     * same rule that made the S7.2 metrics contract publish a closed label
     * instead of the upstream message.
     *
     * The S8.1 read model consumes this store. When it surfaces sync provenance
     * — and it should, because "when was this last measured" is the question the
     * whole table exists for — it must publish the **status and the timestamp**,
     * not this field.
     */
    detail: text('detail'),
  },
  (table) => [
    index('tutorial_syncs_ran_at_idx').on(table.ranAt.desc()),
    check(
      'tutorial_syncs_status_valid',
      sql`${table.status} IN ('ok', 'error')`,
    ),
  ],
);

export type Category = typeof categories.$inferSelect;
export type NewCategory = typeof categories.$inferInsert;
export type Item = typeof items.$inferSelect;
export type NewItem = typeof items.$inferInsert;
export type Player = typeof players.$inferSelect;
export type NewPlayer = typeof players.$inferInsert;
export type Sale = typeof sales.$inferSelect;
export type NewSale = typeof sales.$inferInsert;

/**
 * Every weekly report this system has generated (story S9.2, spec §6.1).
 *
 * ## Why the generated version is stored and not merely sent
 *
 * Criterion 4 of the story asks for it, and the reason is auditability: without
 * a stored copy there is no way to reconstruct **what was known on a given
 * date**. A Discord message can be deleted, edited, or lost in a channel purge,
 * and "we reported the funnel at 12% in the first week of September" stops being
 * a checkable claim the moment the only copy is a chat message.
 *
 * Append-only, like {@link healthChecks} and {@link tutorialSyncs}, and for the
 * same reason: comparing this week against last week is the point.
 *
 * ## An `error` row is a report too
 *
 * A run that could not build its content still writes a row, with `status`
 * `error` and the reason. That is what makes "the job stopped running" different
 * from "the job ran and had nothing to say" — the distinction whose absence let
 * the proxy sit dead for three months. The absence of a row for a week is
 * therefore meaningful, and it means the scheduler itself did not fire.
 *
 * ## `delivered` is separate from `status`
 *
 * A report can build perfectly and fail to reach Discord. Folding the two would
 * make a webhook outage look like an analytics outage, and send whoever reads
 * this table to the wrong system.
 */
export const weeklyReports = pgTable(
  'weekly_reports',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    generatedAt: timestamp('generated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** First day of the reported window, America/Sao_Paulo. */
    periodFrom: date('period_from').notNull(),
    /** Last day of the reported window, inclusive. */
    periodTo: date('period_to').notNull(),
    /** `ok` — content was built. `error` — the run failed before it could be. */
    status: text('status').notNull().$type<'ok' | 'error'>(),
    /**
     * The structured report, exactly as it was assembled.
     *
     * Stored whole rather than as extracted columns: the shape of a report is
     * expected to change as the epic adds layers, and a schema migration per
     * added metric would guarantee that old rows lose the fields they used to
     * carry. What this table is for is answering "what did the report say in
     * September", and that answer has to survive the report changing shape.
     */
    payload: jsonb('payload').$type<Record<string, unknown>>(),
    /** The rendered text that was (or would have been) sent to the channel. */
    rendered: text('rendered'),
    /** Whether the channel actually received it. Distinct from `status`. */
    delivered: boolean('delivered').notNull().default(false),
    /** Why an `error` run failed, in Portuguese. Never a stack trace. */
    detail: text('detail'),
  },
  (table) => [
    // The only two reads: "the latest report" and "the last N reports".
    index('weekly_reports_generated_at_idx').on(table.generatedAt.desc()),
    check(
      'weekly_reports_status_valid',
      sql`${table.status} IN ('ok', 'error')`,
    ),
    // A window that ends before it starts is a bug in the caller, and a report
    // stored with one would silently misdate every number inside it.
    check(
      'weekly_reports_period_ordered',
      sql`${table.periodFrom} <= ${table.periodTo}`,
    ),
  ],
);

/**
 * The `player` dimension of ADR-008 (story S9.1, spec §6.4).
 *
 * ## Why this table exists, in one sentence
 *
 * Sales live in this PostgreSQL and registration dates live in Plan's API, and
 * ADR-008 forbids correlating two live sources in memory — *"o PostgreSQL do
 * `ausTvSales` é o único lugar onde dados de fontes diferentes se cruzam"*. So
 * the registration date has to land here before revenue can be broken down by
 * cohort at all.
 *
 * ## Why it stores a player row when `tutorial_daily` deliberately does not
 *
 * The tutorial table is aggregated at `(day, platform)` precisely to keep player
 * identities out of this database, and the reasoning there is sound: the funnel
 * question is answered by counting.
 *
 * The economy questions are not. *"Quem conclui o tutorial gasta mais?"* and
 * *"quanto tempo até o primeiro gasto?"* are **joins**, and no aggregate of one
 * side can answer them. ADR-008 says so explicitly and names the columns: *"E2
 * exige uma dimensão `player` no Postgres — uuid, platform, first_seen, posição
 * no funil — alimentada por ETL a partir do Plan. É o que torna o cruzamento
 * possível."*
 *
 * ## The footprint this adds, stated plainly
 *
 * It **is** new, and an earlier version of this comment said otherwise by
 * pointing at `sales.player_uuid` and `players.uuid`. Those hold the uuids of
 * people who *bought something*. This table lands the uuid of **every
 * registered player** — ~5.565 — plus two behavioural timestamps each, a whole
 * population that had never appeared in this database.
 *
 * It is permitted: ADR-008 names this dimension by column, and spec §8 allows
 * *"nenhum dado pessoal além de UUID e valor"* for this layer. Nothing here goes
 * beyond that — no nickname, no IP, no session. But "permitted" and "not new"
 * are different claims, and only the first one is true.
 *
 * Saying so matters because this same story argues, in `economy.types.ts`, that
 * per-player tutorial position is the owner's call **on personal-data-footprint
 * grounds**. Two expansions of the same kind cannot be held to opposite
 * standards; the difference is that ADR-008 already decided this one and nothing
 * has decided the other.
 *
 * ⚠️ **There is no retention or deletion policy for this table.** Rows are
 * upserted and never removed. That is a gap for the owner, not a defect of this
 * story.
 *
 * ## Deliberately separate from {@link players}
 *
 * `players` is written by the ingest path and carries a nickname snapshot; every
 * row there is someone who bought something. This table is written by an ETL and
 * must contain players who **never** bought — otherwise the denominator of
 * "share of the cohort that ever spent" would be the buyers themselves, and the
 * answer would always be 100%. Merging the two would also put two writers with
 * different lifecycles on one table.
 *
 * ## Upsert, never delete
 *
 * A player who stops appearing in the payload has not stopped existing. The ETL
 * only inserts and updates; `synced_at` is how a stale row is recognised.
 */
export const playerDimension = pgTable(
  'player_dimension',
  {
    uuid: uuid('uuid').primaryKey(),
    /**
     * `bedrock` | `java_offline` | `java_premium` | `unknown` (ADR-003).
     *
     * Written by the ETL and **read by no query in this application** — the read
     * paths recompute it from the uuid, so that ADR-003 has exactly one
     * implementation and it is the TypeScript one. It is kept because an
     * operator reading this table by hand needs the derived value beside the
     * uuid, and because the index below leads with `registered_at` anyway.
     *
     * No `CHECK` constraint: the only writer is `platformOf`, whose return type
     * is the union. A constraint would be a second spelling of that rule.
     */
    platform: text('platform').notNull(),
    /** `registerDate` from `/v1/retention`. The cohort axis. */
    registeredAt: timestamp('registered_at', { withTimezone: true }).notNull(),
    /**
     * `lastSeenDate` from `/v1/retention`.
     *
     * Not needed by E1 or E2, and stored anyway: E3 compares the D7 of the
     * players who had social contact against everyone else, and that comparison
     * needs this column. Fetching it later would mean a second ETL over the same
     * payload for one field.
     *
     * ⚠️ It is a **survival interval** endpoint, not a return-on-day-N one — see
     * the retention module. Any reader of this column inherits that caveat.
     */
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull(),
    /** When the ETL last wrote this row. How a stale row is recognised. */
    syncedAt: timestamp('synced_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // The cohort axis: "players who registered in month M", by platform.
    index('player_dimension_registered_at_idx').on(
      table.registeredAt,
      table.platform,
    ),
  ],
);

/**
 * Provenance of each player-dimension ETL run (story S9.1).
 *
 * Same reason `tutorial_syncs` exists: an empty {@link playerDimension} is
 * indistinguishable from a sync that never ran, and reading the second as the
 * first turns a collection gap into a reported zero. Every economy read consults
 * this table before publishing a cohort breakdown.
 */
export const playerDimensionSyncs = pgTable(
  'player_dimension_syncs',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    ranAt: timestamp('ran_at', { withTimezone: true }).notNull().defaultNow(),
    /** `ok` — the dimension was refreshed. `error` — nothing was written. */
    status: text('status').notNull().$type<'ok' | 'error'>(),
    /** Rows the payload carried. Null on a run that never got that far. */
    rowsRead: integer('rows_read'),
    /** Rows upserted. */
    rowsWritten: integer('rows_written'),
    /** Rows dropped for an unreadable uuid or date. */
    rowsDropped: integer('rows_dropped'),
    /**
     * Wall-clock duration of the run, milliseconds.
     *
     * Recorded because the S9 Definition of Done asks for timings proving the
     * ETL does not cost the game a tick, and a number nobody wrote down is a
     * number nobody can attach to a PR. This one covers the HTTP path; the
     * MySQL ETL records its own.
     */
    durationMs: integer('duration_ms'),
    /** Why an `error` run failed, in Portuguese. Never a stack trace. */
    detail: text('detail'),
  },
  (table) => [
    index('player_dimension_syncs_ran_at_idx').on(table.ranAt.desc()),
    check(
      'player_dimension_syncs_status_valid',
      sql`${table.status} IN ('ok', 'error')`,
    ),
  ],
);

/**
 * Player-to-player payments, copied from `playerpoints_transaction_log`
 * (story S9.1, ADR-007/ADR-008).
 *
 * ## Why a copy and not a live read
 *
 * The source table **has no index at all** — no primary key, nothing on
 * `receiver`, `timestamp` or `source` (measured 2026-08-21). Any aggregation
 * over it is a full table scan on the MySQL that the Minecraft server itself
 * uses, so ADR-007 forbids reading it live and mandates a nightly ETL into this
 * database, where the indexes are ours.
 *
 * ## Only `PAY_SENDER` and `PAY_RECEIVER` are copied
 *
 * 1.332 rows of 6.664. `OFFSET` carries the administrative grant of 9.999.999
 * that R2 keeps out of every revenue metric, and `SET` is an arrivals series
 * rather than a payment — it lands in {@link accountCreationsDaily} as a count,
 * with no player row at all.
 *
 * ## The natural key, and why the source's lack of one is a real problem
 *
 * A table with no primary key cannot tell a **re-read** from a **second
 * payment**. Two players can genuinely pay the same amount to the same person in
 * the same second, and the log records both as byte-identical rows.
 *
 * So the key here is `(transaction_type, source, receiver, amount, occurred_at,
 * ordinal)`, where `ordinal` counts identical rows within one run, assigned in a
 * deterministic order. Re-running the ETL reproduces the same ordinals — the
 * upsert is a no-op, which is what makes it idempotent — while two genuinely
 * identical payments keep ordinals 0 and 1 and both survive. Collapsing them
 * would silently delete a payment; inventing a surrogate key per run would
 * duplicate every row every night.
 *
 * ## The columns swap between the two rows, and `receiver` is the subject
 *
 * Both measured on 2026-09-02, in two reads.
 *
 * One transfer produces two rows that **trade** `source` and `receiver` and
 * negate the amount, so no reading of those two columns is true for both rows:
 * `transaction_type` has to be pinned before either column means anything.
 *
 * That pair is a perfect mirror and therefore could not settle *which* column is
 * the payer. What did: a `SET` row, which has only one real party and so cannot
 * be symmetric. It comes back `source = NULL` with the player's uuid in
 * `receiver` — making `receiver` the account the entry applies to and `source`
 * the counterparty, absent when there is none. On a `PAY_RECEIVER` row that puts
 * the payer in `source` and the credited account in `receiver`.
 *
 * Both types are still copied verbatim, so a correction later costs a query and
 * not a re-ETL, and the sync record counts each type separately: if the two
 * counts ever diverge, the pairing assumption is wrong and the number says so.
 */
export const playerPayments = pgTable(
  'player_payments',
  {
    /**
     * `PAY_SENDER` or `PAY_RECEIVER`, verbatim from the source.
     *
     * ⚠️ **Filter on this before reading `source` or `receiver`.** Each transfer
     * is logged twice and the two rows SWAP those columns — measured against a
     * real payment on 2026-09-02. A query that ignores the type reads every
     * payment twice, with the two columns meaning opposite things in the two
     * halves of its own result.
     */
    transactionType: text('transaction_type').notNull(),
    /**
     * The counterparty. **Which role that is flips with `transaction_type`**: the
     * payer on a `PAY_RECEIVER` row, the recipient on a `PAY_SENDER` one. Null in
     * the source for actions with no counterparty (`SET`), which is what
     * identified it as the counterparty in the first place.
     */
    source: text('source').notNull(),
    /** The account the entry applies to — the subject. Same flip, mirrored. */
    receiver: text('receiver').notNull(),
    /**
     * Signed amount, in the game's cash unit. Integer in the source.
     *
     * Positive on `PAY_RECEIVER`, negative on `PAY_SENDER` — the sign is what
     * makes the pair self-consistent despite the swapped columns.
     */
    amount: integer('amount').notNull(),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    /** Disambiguates byte-identical rows. See the note above. */
    ordinal: integer('ordinal').notNull(),
    syncedAt: timestamp('synced_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.transactionType,
        table.source,
        table.receiver,
        table.amount,
        table.occurredAt,
        table.ordinal,
      ],
    }),
    // The feed reads "the last N payments"; E3 reads a time window.
    index('player_payments_occurred_at_idx').on(table.occurredAt.desc()),
    // The anomaly marks read "this pair, in this window" and "this sender's
    // distinct receivers" — both lead with the counterparty.
    index('player_payments_source_occurred_at_idx').on(
      table.source,
      table.occurredAt.desc(),
    ),
    index('player_payments_receiver_occurred_at_idx').on(
      table.receiver,
      table.occurredAt.desc(),
    ),
  ],
);

/**
 * Account creations per day, from the `SET` / `Starting balance` rows (R1).
 *
 * ADR-007 calls this an **independent arrivals series**: it is continuous, it
 * comes from a plugin that never stopped writing, and it **covers the Plan
 * blackout of May–July 2026** — the three months where the proxy was dead and
 * the funnel has nothing at all. That makes it a reconciliation source for
 * §6.2, not merely an economy figure.
 *
 * ## Aggregated, with no player row
 *
 * `SET` rows carry a `receiver` uuid, and none of it is stored: the question
 * ("how many accounts were created that day") is answered by counting, and the
 * S8.0 rule applies — spec §8 keeps player identity out of this database
 * wherever a count suffices. That is also why this table is separate from
 * {@link playerPayments}, where the join genuinely needs the uuid.
 *
 * Replaced on every sync, like `tutorial_daily`: the source is a log, so a full
 * recount is the cheapest correct thing and re-running is the normal operation.
 */
export const accountCreationsDaily = pgTable(
  'account_creations_daily',
  {
    /** Calendar day in America/Sao_Paulo. */
    day: date('day').primaryKey(),
    /** `SET` rows on that day. */
    created: integer('created').notNull(),
  },
  (table) => [
    check(
      'account_creations_daily_created_non_negative',
      sql`${table.created} >= 0`,
    ),
  ],
);

/**
 * Provenance of each PlayerPoints ETL run (story S9.1).
 *
 * Same reason the other two provenance tables exist: an empty
 * {@link playerPayments} is indistinguishable from a sync that never ran.
 *
 * `duration_ms` and `source_query_ms` are here because the S9 Definition of Done
 * asks for timings proving the ETL costs the game nothing, and the number has to
 * be written down by the thing that measured it. This is the ETL that actually
 * touches the game's MySQL — the player-dimension one is a single HTTP call —
 * so this is the row that answers that question.
 */
export const playerPaymentSyncs = pgTable(
  'player_payment_syncs',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    ranAt: timestamp('ran_at', { withTimezone: true }).notNull().defaultNow(),
    /** `ok` — payments and the arrivals series were refreshed. */
    status: text('status').notNull().$type<'ok' | 'error'>(),
    /** `PAY_*` rows read from the source. */
    paymentsRead: integer('payments_read'),
    /** Rows upserted into {@link playerPayments}. */
    paymentsWritten: integer('payments_written'),
    /**
     * `PAY_SENDER` and `PAY_RECEIVER` counted apart.
     *
     * They should match one-to-one. If they ever stop matching, the assumption
     * that the two types are the two halves of one payment is wrong, and every
     * social number built on it is wrong with it. Recorded rather than asserted.
     */
    senderRows: integer('sender_rows'),
    receiverRows: integer('receiver_rows'),
    /** `SET` rows counted, feeding {@link accountCreationsDaily}. */
    creationsRead: integer('creations_read'),
    /** Days written to the arrivals series. */
    creationDaysWritten: integer('creation_days_written'),
    /** Wall-clock duration of the whole run, milliseconds. */
    durationMs: integer('duration_ms'),
    /** Time spent inside the MySQL query itself, milliseconds. */
    sourceQueryMs: integer('source_query_ms'),
    /** Why an `error` run failed, in Portuguese. Never a stack trace. */
    detail: text('detail'),
  },
  (table) => [
    index('player_payment_syncs_ran_at_idx').on(table.ranAt.desc()),
    check(
      'player_payment_syncs_status_valid',
      sql`${table.status} IN ('ok', 'error')`,
    ),
  ],
);

/**
 * How far each player got in the tutorial (story S9.3, spec §6.4 E2).
 *
 * ## This table is a deliberate widening of the personal-data footprint
 *
 * `tutorial_daily` is aggregated at `(day, platform)` precisely so that player
 * identities from the game never land in this database, and that decision is
 * right for the funnel — the funnel question is answered by counting.
 *
 * The second half of E2 is not. *"Quem conclui o tutorial gasta mais? Quem trava
 * no passo 03 gasta alguma coisa?"* is a **join** between a player's tutorial
 * position and that same player's purchases, and no aggregate of either side can
 * answer it. So the metric was left unbuilt in story S9.1 and published as
 * `null` with the reason, because widening what §8 governs is the owner's call.
 *
 * **The owner made it on 2026-09-02.** This table is that decision, and it is
 * bounded by it:
 *
 * - **uuid and progress only.** No nickname, no IP, no session, no timestamps
 *   beyond the day of entry — spec §6.4's *"nenhum dado pessoal além de UUID e
 *   valor"*.
 * - **Opt-in on its own switch** (`TUTORIAL_POSITION_ENABLED`), separate from
 *   the tutorial ETL's. A footprint decision deserves a switch of its own; a new
 *   deploy must not start writing player rows because a version changed.
 * - **Replaced on every sync**, like `tutorial_daily`, because the source is
 *   current state rather than an event log.
 *
 * ## Step order is inferred, and the inference is stored
 *
 * `furthest_index` is a position in the catalogue's natural order, which comes
 * from the quest **file names** (`01tutorial` … `33tutorial`) and not from the
 * quests' own requirements. That convention is strong and documented, and it is
 * still a convention — so the resolved order is written into
 * `tutorial_syncs.step_order` on every run, where a human can check it against
 * the game instead of trusting it.
 */
export const tutorialPlayerPosition = pgTable(
  'tutorial_player_position',
  {
    playerUuid: uuid('player_uuid').primaryKey(),
    /** `bedrock` | `java_offline` | `java_premium` | `unknown` (ADR-003). */
    platform: text('platform').notNull(),
    /** Tutorial quests the player has any progress on. */
    questsTouched: integer('quests_touched').notNull(),
    /** Of those, how many are marked completed. */
    questsCompleted: integer('quests_completed').notNull(),
    /**
     * Id of the furthest tutorial quest the player reached, by step order.
     *
     * The id and not only the index, because the index is meaningless without
     * the catalogue that produced it — and the catalogue changes when the
     * tutorial does.
     */
    furthestQuestId: text('furthest_quest_id'),
    /** Position of {@link furthestQuestId} in the catalogue's step order. */
    furthestIndex: integer('furthest_index'),
    /** Whether the configured final quest is completed. */
    completedTutorial: boolean('completed_tutorial').notNull(),
    /** Day the player first touched any tutorial quest. */
    enteredOn: date('entered_on'),
    syncedAt: timestamp('synced_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // The economy read groups by position and by platform.
    index('tutorial_player_position_index_idx').on(
      table.furthestIndex,
      table.platform,
    ),
    check(
      'tutorial_player_position_counts_non_negative',
      sql`${table.questsTouched} >= 0 AND ${table.questsCompleted} >= 0`,
    ),
    // A player in this table touched the tutorial. Zero would mean the row
    // should not exist, and a row that should not exist is a denominator nobody
    // can explain.
    check(
      'tutorial_player_position_touched_positive',
      sql`${table.questsTouched} > 0`,
    ),
  ],
);

/**
 * The five states a suggestion can be in (spec §5.3).
 *
 * Stored as `text` with a check constraint rather than a Postgres enum, to match
 * the rest of this schema and to keep adding a state a plain migration instead of
 * an `ALTER TYPE` that cannot run inside a transaction.
 */
export const SUGGESTION_STATUSES = [
  'enviada',
  'aprovada',
  'em_andamento',
  'concluida',
  'recusada',
] as const;

export type SuggestionStatus = (typeof SUGGESTION_STATUSES)[number];

/** Longest suggestion text accepted on write. Also enforced by a DB check. */
export const SUGGESTION_TEXT_MAX_CHARS = 2000;

/**
 * A player suggestion, as raised in Discord (spec §7).
 *
 * ## `created_at` has no database default, on purpose
 *
 * Every other timestamp in this schema is stamped by the database because it
 * genuinely describes the insert. This one does not: it is the moment the player
 * posted the suggestion, and the row can be written later than that — a bot
 * restart, a replay, a backfill.
 *
 * The `Ticket-Bot` has the failure this omission prevents: `message.ts:13` uses
 * `default: Date.now`, so an insert that forgets the date silently stores the
 * insert time and nothing ever looks wrong. Here, forgetting it is a `NOT NULL`
 * violation at the first write. See {@link updatedAt}, which is the opposite
 * case and does default.
 *
 * ## Identity
 *
 * `author` and `assignee` hold **Discord user ids** (snowflakes), never display
 * names. §8 allows an identifier and nothing more, and a display name is both
 * personal data and mutable — the audit trail the states need has to survive a
 * nickname change. The `Ticket-Bot` logs `displayName` today; that is the
 * pattern this column exists not to repeat.
 *
 * ## Sanitization
 *
 * `text` is player-controlled. It is sanitized on write by
 * `sanitizeSuggestionText`, and the consumer still escapes on render — §8 asks
 * for both, because sanitizing cannot know the target syntax and escaping cannot
 * undo a control character already stored.
 */
export const suggestions = pgTable(
  'suggestions',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    /**
     * Id of the Discord message the suggestion came from.
     *
     * Unique: it is the natural key of the source event, so a bot that replays
     * (reconnect, restart, double dispatch) cannot create a second row for the
     * same suggestion.
     */
    discordMsgId: text('discord_msg_id').notNull(),
    /** Discord user id of the author — an identifier, never a display name. */
    author: text('author').notNull(),
    /** Player-written body, already sanitized. Escaped again at render time. */
    text: text('text').notNull(),
    votesUp: integer('votes_up').notNull().default(0),
    votesDown: integer('votes_down').notNull().default(0),
    /** One of {@link SUGGESTION_STATUSES}; new suggestions start at `enviada`. */
    status: text('status')
      .$type<SuggestionStatus>()
      .notNull()
      .default('enviada'),
    /** When the player posted it — **not** when the row was written. */
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    /**
     * When this row last changed - genuinely the write time, and the exact
     * opposite case from {@link createdAt}.
     *
     * `$onUpdate` and not a database trigger, so it is maintained by Drizzle on
     * every `db.update()`. That covers every writer this table is meant to have;
     * a hand-written `UPDATE` in `psql` bypasses it, which is the honest limit
     * of the mechanism. Without it the column would be documented as "last
     * changed" and hold the insert time forever - a plausible wrong date, which
     * is the failure this table exists not to repeat.
     */
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    /** Discord user id of the staff member who took it, if any. */
    assignee: text('assignee'),
  },
  (table) => [
    uniqueIndex('suggestions_discord_msg_id_unique').on(table.discordMsgId),
    // The listing filters by state and orders by date (S10.3, S11.1).
    index('suggestions_status_created_at_idx').on(
      table.status,
      table.createdAt,
    ),
    check(
      'suggestions_status_valid',
      sql`${table.status} IN ('enviada', 'aprovada', 'em_andamento', 'concluida', 'recusada')`,
    ),
    check(
      'suggestions_votes_non_negative',
      sql`${table.votesUp} >= 0 AND ${table.votesDown} >= 0`,
    ),
    // A suggestion with no text is not a suggestion. The sanitizer rejects it
    // too; this is the backstop for any write path that skips the sanitizer.
    //
    // The whitespace set is spelled out, and it is spelled out to be **exactly**
    // the set `String.prototype.trim()` strips. Bare `btrim(x)` trims spaces
    // only, so a value of a single newline passed the first version of this
    // constraint and CI caught it; `[:space:]` would have been collation
    // dependent, and would still not cover U+00A0. Enumerated, the two rules are
    // the same rule, and `suggestion-text.spec.ts` asserts they stay that way.
    check(
      'suggestions_text_present',
      sql`btrim(${table.text}, E'\\u0009\\u000A\\u000B\\u000C\\u000D\\u0020\\u00A0\\u1680\\u2000\\u2001\\u2002\\u2003\\u2004\\u2005\\u2006\\u2007\\u2008\\u2009\\u200A\\u2028\\u2029\\u202F\\u205F\\u3000\\uFEFF') <> ''`,
    ),
    check(
      'suggestions_text_max_length',
      sql`length(${table.text}) <= ${sql.raw(String(SUGGESTION_TEXT_MAX_CHARS))}`,
    ),
  ],
);

export type Suggestion = typeof suggestions.$inferSelect;
export type NewSuggestion = typeof suggestions.$inferInsert;
