import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import type {
  HealthCheckDetail,
  HealthCheckStatus,
} from '../instrumentation/health-check.types';

/**
 * Database schema for austv-sales (spec section 4).
 *
 * Design invariants enforced here (see .specs/project/PROJECT.md §4, §7):
 * - `sales.id` is a client-supplied UUID (generated by the plugin) — no DB default.
 *   The primary key is the sole idempotency guard against the SQLite queue replay.
 * - `sales.item_id` references `items.item_id` (the opaque business key), not `items.id`.
 * - `purchased_at` comes from the plugin payload; `created_at` is stamped by the DB
 *   so we can audit queue latency without polluting the real purchase timestamp.
 * - All timestamps are `timestamptz` (clock-skew / America/Sao_Paulo correctness).
 * - All foreign keys are ON DELETE NO ACTION (the pg default): a category cannot be
 *   deleted while items reference it, nor an item while sales reference it. Catalog is
 *   deactivated (`active = false`), never hard-deleted — historical sales stay intact.
 */

export const categories = pgTable(
  'categories',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    name: text('name').notNull(),
    displayOrder: integer('display_order').notNull().default(0),
  },
  (table) => [
    // Case-insensitive uniqueness of the category name (spec S4.0). The service
    // pre-checks to produce a friendly 409, but the check-then-insert pair is a
    // race: this index is the data-layer guarantee that a duplicate can never
    // land, no matter how the write arrives.
    uniqueIndex('categories_name_lower_unique').on(sql`lower(${table.name})`),
  ],
);

export const items = pgTable('items', {
  id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
  itemId: text('item_id').notNull().unique(),
  displayName: text('display_name').notNull(),
  categoryId: integer('category_id')
    .notNull()
    .references(() => categories.id),
  active: boolean('active').notNull().default(true),
});

export const players = pgTable('players', {
  uuid: uuid('uuid').primaryKey(),
  lastKnownNickname: text('last_known_nickname').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const sales = pgTable(
  'sales',
  {
    // Client-supplied UUID (plugin-generated). No default: the plugin owns the id
    // so that reprocessing the SQLite fallback queue is idempotent (spec §3, §7).
    id: uuid('id').primaryKey(),
    itemId: text('item_id')
      .notNull()
      .references(() => items.itemId),
    playerUuid: uuid('player_uuid')
      .notNull()
      .references(() => players.uuid),
    nicknameAtPurchase: text('nickname_at_purchase').notNull(),
    totalPrice: numeric('total_price', { precision: 12, scale: 2 }).notNull(),
    qtd: integer('qtd').notNull(),
    purchasedAt: timestamp('purchased_at', { withTimezone: true }).notNull(),
    historicalImport: boolean('historical_import').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index('sales_item_purchased_at_idx').on(table.itemId, table.purchasedAt),
    index('sales_player_item_idx').on(table.playerUuid, table.itemId),
    // Data-layer defense for financial integrity (spec §2, §7): a bug or a
    // replayed queue entry must never persist a non-positive amount/quantity.
    check('sales_qtd_positive', sql`${table.qtd} > 0`),
    check('sales_total_price_positive', sql`${table.totalPrice} > 0`),
  ],
);

/**
 * Instrumentation health checks (AusTV Admin spec §6.1, ADR-006 — story S6.3).
 *
 * The table is **append-only**: one row per check execution. That choice is the
 * whole point of ADR-006 — every disaster found at AusTV was silent for months,
 * so "what did this check say last week?" has to be answerable. Keeping a
 * current-state row and overwriting it would answer only "what does it say now",
 * which is exactly the blindness the epic exists to remove. The current state of
 * a check is simply its most recent row.
 *
 * `alerted_at` is per-observation, not per-check: it records whether *this*
 * reading was announced on Discord. That is what lets the alerter group a
 * three-month outage into one notification instead of one per cycle, without
 * losing the fact that the check kept running the whole time.
 *
 * Table name is plural to match the rest of this schema; the spec §7 sketch
 * writes entities in the singular (`health_check`).
 */
export const healthChecks = pgTable(
  'health_checks',
  {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    /** Stable identifier of the check (see `HealthCheckName`). */
    checkName: text('check_name').notNull().$type<string>(),
    status: text('status').notNull().$type<HealthCheckStatus>(),
    checkedAt: timestamp('checked_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    /**
     * Structured verdict. Deliberately jsonb rather than free text so a ratio can
     * always carry the `n` behind it — the spec rule is that no percentage is
     * ever published without its base.
     */
    detail: jsonb('detail').$type<HealthCheckDetail>(),
    /** When this observation produced a Discord alert; null means it did not. */
    alertedAt: timestamp('alerted_at', { withTimezone: true }),
  },
  (table) => [
    // Serves both access patterns: "latest row for this check" and "history of
    // this check", which are the only two ways this table is ever read.
    index('health_checks_name_checked_at_idx').on(
      table.checkName,
      table.checkedAt.desc(),
    ),
    // `no_data` and `error` exist as first-class states on purpose. A gap in
    // collection must never be recorded as `ok` (false confidence) nor as a zero
    // reading (a fabricated measurement) — the two failure modes ADR-006 targets.
    check(
      'health_checks_status_valid',
      sql`${table.status} IN ('ok', 'breached', 'no_data', 'error')`,
    ),
  ],
);

export type Category = typeof categories.$inferSelect;
export type NewCategory = typeof categories.$inferInsert;
export type Item = typeof items.$inferSelect;
export type NewItem = typeof items.$inferInsert;
export type Player = typeof players.$inferSelect;
export type NewPlayer = typeof players.$inferInsert;
export type Sale = typeof sales.$inferSelect;
export type NewSale = typeof sales.$inferInsert;
