/**
 * Sale event, as returned by the `austv-sales` API.
 *
 * Field names mirror the `sales` table columns described in
 * `.specs/project/PROJECT.md` (snake_case), since the backend contract for
 * response serialization has not been decided yet. Revisit if the backend
 * adopts camelCase DTOs.
 */
export interface Sale {
  /** UUID generated by the plugin at command execution time (idempotency key). */
  sale_id: string;
  /** Opaque item identifier (e.g. `caixaNatal2026`). */
  item_id: string;
  /** UUID of the buyer, used as the aggregation key. */
  player_uuid: string;
  /** Snapshot of the buyer's nickname at purchase time. */
  nickname_at_purchase: string;
  /** Total transaction value, regardless of quantity. */
  total_price: number;
  /** Quantity of items purchased in this transaction. */
  qtd: number;
  /** ISO 8601 timestamp captured by the plugin at purchase time. */
  purchased_at: string;
  /** True for events created by the one-time historical migration. */
  historical_import: boolean;
}
